## 기상청 (대전, 청주, 보은)

In [16]:
import pandas as pd
import numpy as np

# 파일 읽기
df = pd.read_csv("기상청 자료 (대전, 충주, 보은).csv",encoding="cp949")

df

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),합계 일사량(MJ/m2),평균 전운량(1/10)
0,131,청주,2016-01-01,1.5,-4.2,6.2,NaN,0.8,68.1,5.4,7.49,5.6
1,131,청주,2016-01-02,6.0,1.4,11.5,NaN,0.9,65.5,5.6,5.57,6.1
2,131,청주,2016-01-03,6.5,2.0,11.3,NaN,0.7,77.8,4.3,6.10,5.5
3,131,청주,2016-01-04,4.4,0.3,7.0,NaN,1.7,51.0,7.5,7.85,4.9
4,131,청주,2016-01-05,-0.6,-2.3,2.7,NaN,1.5,32.0,5.3,7.38,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10957,226,보은,2025-12-28,1.9,-1.1,6.7,0.0,0.2,87.6,1.1,NaN,6.9
10958,226,보은,2025-12-29,2.8,-1.2,9.1,1.1,0.7,91.6,1.0,NaN,5.9
10959,226,보은,2025-12-30,-1.0,-5.5,4.4,NaN,1.1,65.1,8.7,NaN,0.1
10960,226,보은,2025-12-31,-4.5,-8.9,-1.2,NaN,1.8,51.9,8.8,NaN,0.3
10961,226,보은,2026-01-01,-7.0,-11.7,-2.6,NaN,1.5,52.9,8.4,NaN,2.5

In [ ]:
df['일시'] = pd.to_datetime(df['일시'])
df['일강수량(mm)'] = df['일강수량(mm)'].fillna(0)

In [8]:
numeric_cols = [
    '평균기온(°C)', '최저기온(°C)', '최고기온(°C)',
    '일강수량(mm)', '평균 풍속(m/s)',
    '평균 상대습도(%)', '합계 일조시간(hr)',
    '합계 일사량(MJ/m2)', '평균 전운량(1/10)'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [19]:
weather_daily = (
    df
    .groupby('일시')
    .agg({
        '평균기온(°C)': 'mean',
        '최저기온(°C)': 'mean',
        '최고기온(°C)': 'mean',
        '일강수량(mm)': 'mean',
        '평균 풍속(m/s)': 'mean',
        '평균 상대습도(%)': 'mean',
        '합계 일조시간(hr)': 'mean',
        '합계 일사량(MJ/m2)': 'mean',
        '평균 전운량(1/10)': 'mean'
    })
    .reset_index()
    .sort_values('일시')
)
#weather_daily = weather_daily.iloc[:-1]

print(weather_daily.shape)
weather_daily.tail()

(3653, 10)

,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),합계 일사량(MJ/m2),평균 전운량(1/10)
3648,2025-12-27,-2.766667,-8.666667,0.900000,0.066667,0.633333,71.066667,2.466667,4.795,7.433333
3649,2025-12-28,3.166667,-0.633333,8.133333,0.050000,0.566667,79.000000,1.800000,6.235,7.100000
3650,2025-12-29,4.500000,0.733333,10.466667,0.766667,1.066667,81.766667,1.600000,4.970,5.000000
3651,2025-12-30,0.100000,-3.366667,5.133333,NaN,1.366667,50.633333,8.300000,11.360,0.300000
3652,2025-12-31,-3.766667,-7.566667,-0.566667,NaN,2.133333,45.033333,8.266667,11.725,1.066667

In [ ]:
#weather_daily.to_csv("weather_processed.csv", index=False, encoding="utf-8-sig")

##

## 수자원공사_조류데이터

In [44]:
# 파일 읽기
df = pd.read_excel("댐 조류 모니터링.xlsx")
df.columns = df.columns.get_level_values(0)
df = df.reset_index(drop=True)
df["조사일"] = pd.to_datetime(df["조사일"])

df.head()

,채수위치,조사일,일조시간 합계(hr),일강수량(mm),수온(℃),pH,DO(㎎/L),투명도,탁도,Chl-a (㎎/㎥),발령단계,유해남조류 \n세포수 (cells/㎖)\n(1+2+3+4),(1)\nMicrocystis,(2)\nAnabaena,(3)\nOscillatoria,(4)\nAphanizomenon
0,문의,2016-01-05,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,미발령,108.0,0.0,0.0,0.0,108.0
1,문의,2016-01-11,8.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,미발령,134.0,0.0,0.0,0.0,134.0
2,문의,2016-01-18,3.6,2.0,NaN,NaN,NaN,NaN,NaN,NaN,미발령,26.0,0.0,0.0,0.0,26.0
3,문의,2016-01-25,9.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,미발령,0.0,0.0,0.0,0.0,0.0
4,문의,2016-02-01,9.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,미발령,0.0,0.0,0.0,0.0,0.0

In [ ]:
# 2. 컬럼 이름 수정
df.columns = df.columns.str.replace("\n", "").str.strip()

# 컬럼 rename (핵심만)
df = df.rename(columns={
    "유해남조류 세포수 (cells/㎖)(1+2+3+4)": "total_cyano",
    "(1)Microcystis": "microcystis",
    "(2)Anabaena": "anabaena",
    "(3)Oscillatoria": "oscillatoria",
    "(4)Aphanizomenon": "aphanizomenon"
})

# 날짜 변환
df["조사일"] = pd.to_datetime(df["조사일"])

# 정렬
df = df.sort_values(["채수위치", "조사일"])

In [ ]:
# 3. 주 → 일 변환 (growth)
def expand_to_daily(df, target_cols):
    results = []

    for site, group in df.groupby("채수위치"):
        group = group.sort_values("조사일").reset_index(drop=True)

        for i in range(len(group) - 1):
            row_start = group.iloc[i]
            row_end = group.iloc[i + 1]

            start = row_start["조사일"]
            end = row_end["조사일"]
            days = (end - start).days

            date_range = pd.date_range(start=start, end=end, freq="D")

            temp = pd.DataFrame({"조사일": date_range})
            temp["채수위치"] = site

            for col in target_cols:
                y0 = row_start[col]
                y1 = row_end[col]

                eps = 1e-6
                y0, y1 = y0 + eps, y1 + eps

                r = np.log(y1 / y0) / days if days > 0 else 0
                temp[col] = [y0 * np.exp(r * t) for t in range(days + 1)]

            results.append(temp.iloc[:-1])

        results.append(group.iloc[-1:])

    return pd.concat(results).reset_index(drop=True)


target_cols = ["total_cyano", "microcystis", "anabaena", "oscillatoria", "aphanizomenon"]
df_daily = expand_to_daily(df, target_cols)

In [ ]:
# 4. 수질 데이터 merge
quality_cols = ["채수위치", "조사일"]

for col in df.columns:
    if any(x in col for x in ["수온", "pH", "DO", "탁도", "Chl-a"]):
        quality_cols.append(col)

df_daily = df_daily.merge(df[quality_cols], on=["채수위치", "조사일"], how="left")

# 5. 수질 보간
quality_features = [col for col in df_daily.columns if any(x in col for x in ["수온", "pH", "DO", "탁도", "Chl-a"])]

df_daily = df_daily.sort_values(["채수위치", "조사일"])

df_daily[quality_features] = (
    df_daily
    .groupby("채수위치")[quality_features]
    .transform(lambda x: x.interpolate().bfill().ffill())
)

In [ ]:
# 6. 발령단계
def classify_alert(x):
    if x >= 1_000_000:
        return "조류대발생"
    elif x >= 10_000:
        return "경계"
    elif x >= 1_000:
        return "관심"
    else:
        return "미발령"

df_daily["발령단계"] = df_daily["total_cyano"].apply(classify_alert)

In [ ]:
# 칼럼정리
df_daily["수온(℃)"] = df_daily["수온(℃)_y"]
df_daily["pH"] = df_daily["pH_y"]
df_daily["DO(㎎/L)"] = df_daily["DO(㎎/L)_y"]
df_daily["탁도"] = df_daily["탁도_y"]
df_daily["Chl-a (㎎/㎥)"] = df_daily["Chl-a (㎎/㎥)_y"]

df_daily = df_daily.drop(columns=[
    "수온(℃)_x", "수온(℃)_y",
    "pH_x", "pH_y",
    "DO(㎎/L)_x", "DO(㎎/L)_y",
    "탁도_x", "탁도_y",
    "Chl-a (㎎/㎥)_x", "Chl-a (㎎/㎥)_y"
], errors="ignore")

cols = ["수온(℃)", "pH", "DO(㎎/L)", "탁도", "Chl-a (㎎/㎥)"]

df_daily[cols] = (
    df_daily
    .groupby("채수위치")[cols]
    .transform(lambda x: x.interpolate().bfill().ffill())
)

In [86]:
df_daily.head()

,조사일,채수위치,total_cyano,microcystis,anabaena,oscillatoria,aphanizomenon,일조시간 합계(hr),일강수량(mm),투명도,발령단계,alert_binary,log_total_cyano,수온(℃),pH,DO(㎎/L),탁도,Chl-a (㎎/㎥)
0,2016-01-05,문의,108.000001,0.000001,0.000001,0.000001,108.000001,NaN,NaN,NaN,미발령,0,4.691348,8.8,8.2,13.3,1.7,4.5
1,2016-01-06,문의,111.953395,0.000001,0.000001,0.000001,111.953395,NaN,NaN,NaN,미발령,0,4.726975,8.8,8.2,13.3,1.7,4.5
2,2016-01-07,문의,116.051504,0.000001,0.000001,0.000001,116.051504,NaN,NaN,NaN,미발령,0,4.762614,8.8,8.2,13.3,1.7,4.5
3,2016-01-08,문의,120.299627,0.000001,0.000001,0.000001,120.299627,NaN,NaN,NaN,미발령,0,4.798264,8.8,8.2,13.3,1.7,4.5
4,2016-01-09,문의,124.703254,0.000001,0.000001,0.000001,124.703254,NaN,NaN,NaN,미발령,0,4.833924,8.8,8.2,13.3,1.7,4.5

In [90]:
df_daily.to_csv("조류_preprocessed.csv", index=False, encoding="utf-8-sig")

## 수문정보 데이터

In [95]:
df_hydro = pd.read_csv("한국수자원공사) 대청댐 운영 수문정보.csv")
df_hydro["관측년월일"] = pd.to_datetime(df_hydro["관측년월일"])
df_hydro = df_hydro[
    (df_hydro["관측년월일"] >= "2016-01-01") &
    (df_hydro["관측년월일"] <= "2025-12-31")
]

In [97]:
df_hydro = df_hydro.rename(columns={
    "관측년월일": "조사일"
})

In [98]:
df_hydro.to_csv("수문정보_preprocessed.csv", index=False, encoding="utf-8-sig")

# 데이터 합치기

In [99]:
weather_daily

,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),합계 일조시간(hr),합계 일사량(MJ/m2),평균 전운량(1/10)
0,2016-01-01,0.533333,-5.366667,6.866667,NaN,0.833333,74.833333,4.600000,8.355,5.550000
1,2016-01-02,5.433333,0.566667,12.300000,NaN,0.933333,72.466667,6.166667,6.760,5.700000
2,2016-01-03,6.033333,0.833333,13.066667,NaN,0.766667,79.900000,5.866667,7.710,4.750000
3,2016-01-04,4.400000,-1.166667,8.400000,NaN,1.833333,56.700000,6.966667,9.130,4.250000
4,2016-01-05,-0.933333,-3.900000,3.133333,NaN,1.400000,40.733333,4.833333,7.550,4.250000
...,...,...,...,...,...,...,...,...,...,...
3648,2025-12-27,-2.766667,-8.666667,0.900000,0.066667,0.633333,71.066667,2.466667,4.795,7.433333
3649,2025-12-28,3.166667,-0.633333,8.133333,0.050000,0.566667,79.000000,1.800000,6.235,7.100000
3650,2025-12-29,4.500000,0.733333,10.466667,0.766667,1.066667,81.766667,1.600000,4.970,5.000000
3651,2025-12-30,0.100000,-3.366667,5.133333,NaN,1.366667,50.633333,8.300000,11.360,0.300000
3652,2025-12-31,-3.766667,-7.566667,-0.566667,NaN,2.133333,45.033333,8.266667,11.725,1.066667

In [100]:
df_daily

,조사일,채수위치,total_cyano,microcystis,anabaena,oscillatoria,aphanizomenon,일조시간 합계(hr),일강수량(mm),투명도,발령단계,수온(℃),pH,DO(㎎/L),탁도,Chl-a (㎎/㎥)
0,2016-01-05,문의,108.000001,0.000001,0.000001,0.000001,108.000001,NaN,NaN,NaN,미발령,8.8,8.200000,13.300000,1.700000,4.5
1,2016-01-06,문의,111.953395,0.000001,0.000001,0.000001,111.953395,NaN,NaN,NaN,미발령,8.8,8.200000,13.300000,1.700000,4.5
2,2016-01-07,문의,116.051504,0.000001,0.000001,0.000001,116.051504,NaN,NaN,NaN,미발령,8.8,8.200000,13.300000,1.700000,4.5
3,2016-01-08,문의,120.299627,0.000001,0.000001,0.000001,120.299627,NaN,NaN,NaN,미발령,8.8,8.200000,13.300000,1.700000,4.5
4,2016-01-09,문의,124.703254,0.000001,0.000001,0.000001,124.703254,NaN,NaN,NaN,미발령,8.8,8.200000,13.300000,1.700000,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10915,2025-12-18,회남,0.060443,0.055392,0.000001,0.000001,0.019783,NaN,NaN,NaN,미발령,11.4,7.657143,9.485714,3.114286,6.1
10916,2025-12-19,회남,0.003855,0.003611,0.000001,0.000001,0.001668,NaN,NaN,NaN,미발령,11.2,7.642857,9.514286,2.985714,6.1
10917,2025-12-20,회남,0.000246,0.000235,0.000001,0.000001,0.000141,NaN,NaN,NaN,미발령,11.0,7.628571,9.542857,2.857143,6.1
10918,2025-12-21,회남,0.000016,0.000015,0.000001,0.000001,0.000012,NaN,NaN,NaN,미발령,10.8,7.614286,9.571429,2.728571,6.1
10919,2025-12-22,회남,0.000000,0.000000,0.000000,0.000000,0.000000,8.0,NaN,3.7,미발령,10.6,7.600000,9.600000,2.600000,6.1

In [101]:
df_hydro

,조사일,댐코드,댐명,저수위,저수량,유입량,총방류량,저수율,전년저수위,예년저수위,...,기타방류량1,기타방류량2,기타방류량3,취수량1,취수량2,취수량3,outlet방류량,07시강수량,예년강수량,기타발전방류량
0,2025-11-07,3008110,대청,75.0890,1105.2745,26.364,26.364,74.18,74.2768,72.6063,...,0,0,0.0,6.052,4.754,0.908,0,NaN,1.3959,0
1,2025-11-06,3008110,대청,75.0890,1105.2745,28.121,33.117,74.18,74.2869,72.6205,...,0,0,0.0,6.064,4.698,0.905,0,NaN,2.5758,0
2,2025-11-05,3008110,대청,75.0959,1105.7061,31.616,32.630,74.21,74.3050,72.6349,...,0,0,0.0,5.590,4.691,0.905,0,NaN,1.5673,0
3,2025-11-04,3008110,대청,75.0973,1105.7937,23.616,32.090,74.21,74.3228,72.6496,...,0,0,0.0,5.070,4.742,0.851,0,NaN,0.1808,0
4,2025-11-03,3008110,대청,75.1090,1106.5258,32.367,32.367,74.26,74.3388,72.6711,...,0,0,0.0,6.030,4.680,0.221,0,NaN,0.3454,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3594,2016-01-05,3008110,대청,66.2200,616.7980,14.020,19.026,41.40,73.2200,69.4300,...,0,0,0.0,5.278,4.323,0.000,0,NaN,0.8970,0
3595,2016-01-04,3008110,대청,66.2300,617.2310,18.990,18.990,41.40,73.2400,69.4500,...,0,0,0.0,5.117,4.335,0.000,0,NaN,0.6055,0
3596,2016-01-03,3008110,대청,66.2300,617.2310,19.126,19.126,41.40,73.2600,69.4700,...,0,0,0.0,5.243,4.455,0.000,0,NaN,0.5180,0
3597,2016-01-02,3008110,대청,66.2300,617.2310,23.881,18.875,41.40,73.2800,69.4800,...,0,0,0.0,4.954,4.345,0.000,0,NaN,1.2844,0
3598,2016-01-01,3008110,대청,66.2200,616.7980,19.370,19.370,41.40,73.3100,69.5000,...,0,0,0.0,5.440,4.419,0.000,0,NaN,0.6743,0

In [103]:
df=pd.read_csv("댐 운영_processed.csv")
df

              일시  수위(EL.m)   저수량(백만㎥)  저수율(%)  강우량(mm)  유입량(㎥/s)  총방류량(㎥/s)
0     2016-01-01   66.2200   616.7980   41.40   0.0000    19.370     19.370
1     2016-01-02   66.2300   617.2310   41.40   0.0000    23.881     18.875
2     2016-01-03   66.2300   617.2310   41.40   0.0000    19.126     19.126
3     2016-01-04   66.2300   617.2310   41.40   0.0000    18.990     18.990
4     2016-01-05   66.2200   616.7980   41.40   0.0000    14.020     19.026
...          ...       ...        ...     ...      ...       ...        ...
3648  2025-12-27   74.3080  1057.0509   70.94   0.0000    17.850     33.233
3649  2025-12-28   74.2969  1056.3745   70.90   0.1315    25.291     33.119
3650  2025-12-29   74.2800  1055.3452   70.83   1.7101    21.339     33.252
3651  2025-12-30   74.2629  1054.3043   70.76   0.0273    21.172     33.219
3652  2025-12-31   74.2390  1052.8505   70.66   0.0000    16.441     33.268

[3653 rows x 7 columns]

In [104]:
# =========================
# 0. 날짜 정리
# =========================
df_daily["조사일"] = pd.to_datetime(df_daily["조사일"])
weather_daily["일시"] = pd.to_datetime(weather_daily["일시"])
df["일시"] = pd.to_datetime(df["일시"])

# =========================
# 1. 컬럼 이름 통일
# =========================
weather_daily = weather_daily.rename(columns={"일시": "조사일"})
df = df.rename(columns={"일시": "조사일"})

# =========================
# 2. merge 시작
# =========================
df_final = df_daily.copy()

# (1) 기상
df_final = df_final.merge(
    weather_daily,
    on="조사일",
    how="left"
)

# (2) 수문
df_final = df_final.merge(
    df,
    on="조사일",
    how="left"
)

# =========================
# 3. 정렬
# =========================
df_final = df_final.sort_values(["채수위치", "조사일"])

# =========================
# 4. 확인
# =========================
print("shape:", df_final.shape)
df_final.head()

shape: (10920, 31)

,조사일,채수위치,total_cyano,microcystis,anabaena,oscillatoria,aphanizomenon,일조시간 합계(hr),일강수량(mm)_x,투명도,...,평균 상대습도(%),합계 일조시간(hr),합계 일사량(MJ/m2),평균 전운량(1/10),수위(EL.m),저수량(백만㎥),저수율(%),강우량(mm),유입량(㎥/s),총방류량(㎥/s)
0,2016-01-05,문의,108.000001,0.000001,0.000001,0.000001,108.000001,NaN,NaN,NaN,...,40.733333,4.833333,7.550,4.25,66.22,616.798,41.4,0.0,14.020,19.026
1,2016-01-06,문의,111.953395,0.000001,0.000001,0.000001,111.953395,NaN,NaN,NaN,...,57.866667,3.966667,6.990,7.05,66.22,616.798,41.4,0.0,19.239,19.239
2,2016-01-07,문의,116.051504,0.000001,0.000001,0.000001,116.051504,NaN,NaN,NaN,...,53.733333,7.433333,10.080,4.10,66.22,616.798,41.4,0.0,19.406,19.406
3,2016-01-08,문의,120.299627,0.000001,0.000001,0.000001,120.299627,NaN,NaN,NaN,...,55.133333,7.966667,9.340,4.55,66.21,616.366,41.4,0.0,14.447,19.450
4,2016-01-09,문의,124.703254,0.000001,0.000001,0.000001,124.703254,NaN,NaN,NaN,...,56.433333,6.100000,8.935,7.15,66.21,616.366,41.4,0.0,19.510,19.510

In [118]:
df_final["일강수량(mm)"] = df_final["일강수량(mm)_y"]
df_final = df_final.drop(columns=[
    "일강수량(mm)_x",
    "일강수량(mm)_y"
], errors="ignore")

In [119]:
df_final.columns

Index(['조사일', '채수위치', 'total_cyano', 'microcystis', 'anabaena', 'oscillatoria',
       'aphanizomenon', '일조시간 합계(hr)', '투명도', '발령단계', '수온(℃)', 'pH', 'DO(㎎/L)',
       '탁도', 'Chl-a (㎎/㎥)', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '평균 풍속(m/s)',
       '평균 상대습도(%)', '합계 일조시간(hr)', '합계 일사량(MJ/m2)', '평균 전운량(1/10)',
       '수위(EL.m)', '저수량(백만㎥)', '저수율(%)', '강우량(mm)', '유입량(㎥/s)', '총방류량(㎥/s)',
       '일강수량(mm)'],
      dtype='object')

In [120]:
df_final.head()

,조사일,채수위치,total_cyano,microcystis,anabaena,oscillatoria,aphanizomenon,일조시간 합계(hr),투명도,발령단계,...,합계 일조시간(hr),합계 일사량(MJ/m2),평균 전운량(1/10),수위(EL.m),저수량(백만㎥),저수율(%),강우량(mm),유입량(㎥/s),총방류량(㎥/s),일강수량(mm)
0,2016-01-05,문의,108.000001,0.000001,0.000001,0.000001,108.000001,NaN,NaN,미발령,...,4.833333,7.550,4.25,66.22,616.798,41.4,0.0,14.020,19.026,NaN
1,2016-01-06,문의,111.953395,0.000001,0.000001,0.000001,111.953395,NaN,NaN,미발령,...,3.966667,6.990,7.05,66.22,616.798,41.4,0.0,19.239,19.239,NaN
2,2016-01-07,문의,116.051504,0.000001,0.000001,0.000001,116.051504,NaN,NaN,미발령,...,7.433333,10.080,4.10,66.22,616.798,41.4,0.0,19.406,19.406,NaN
3,2016-01-08,문의,120.299627,0.000001,0.000001,0.000001,120.299627,NaN,NaN,미발령,...,7.966667,9.340,4.55,66.21,616.366,41.4,0.0,14.447,19.450,0.0
4,2016-01-09,문의,124.703254,0.000001,0.000001,0.000001,124.703254,NaN,NaN,미발령,...,6.100000,8.935,7.15,66.21,616.366,41.4,0.0,19.510,19.510,0.0

In [121]:
df_final.to_csv("finaldata.csv", index=False, encoding="utf-8-sig")